sudo: required
language: c
compiler:
  - gcc
  - clang
before_install:
    - sudo echo deb http://http.us.debian.org/debian/ buster main >> /etc/apt/sources.list
    - sudo apt-get -qq update
install:
    - sudo apt-get -qq install rake bison git gperf libjwt-dev
before_script:
  - cd ../
  - git clone --depth 1 https://github.com/mruby/mruby.git
  - cd mruby
  - cp -fp ../mruby-libjwt/.travis_build_config.rb build_config.rb
script:
  - make all test
